const KEY='bird_dashboard_rebuild_v1';
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{entries:[],tasks:{},invoices:[],services:['Weed Eating','Mowing','Painting','Leaf Blowing','Yard Clean','General Labor','Debris Removal','Gutters','Handyman','Other'],supplies:['Gas','Oil','String','Other'],equipment:['Trimmer','Mower','Chainsaw','Loppers','Shovel','Drill','Other'],labor:['Lot Size','Time']};
let currentMonth=new Date(), selectedDate=iso(new Date()), activeServices=[],activeSupplies=[],activeEquipment=[],activeLabor=[],sigCanvas,sigCtx,drawing=false,checkPhotoData='',autoTimer=null,autoInvTimer=null;
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function uid(){return crypto.randomUUID?crypto.randomUUID():'id'+Date.now()+Math.random()}
function iso(d){let x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}
function money(n){return '$'+Number(n||0).toFixed(2)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function safe(s){return String(s).replaceAll("\\","\\\\").replaceAll("'","\\'")}
function showView(v){dashboardView.classList.toggle('hidden',v!=='dashboard');invoiceView.classList.toggle('hidden',v!=='invoices');dashBtn.className=v==='dashboard'?'active':'';invBtn.className=v==='invoices'?'active':'';if(v==='invoices'){renderInvoiceBuilder();renderInvoices();setupSignature();if(!invDate.value)newInvoice()}}
function showClientTab(t){clientInfoBox.classList.toggle('hidden',t!=='info');clientInvoiceBox.classList.toggle('hidden',t!=='invoices');clientInfoTab.className=t==='info'?'active':'';clientInvTab.className=t==='invoices'?'active':''}
function render(){renderCalendar();renderAgenda();renderTasks();renderTrackers();renderClientList();renderClientArea();renderInvoices()}
function renderTrackers(){let h=0,p=0,o=0;db.entries.forEach(e=>{if(e.type==='completed'){h+=Number(e.hours||0);p+=Number(e.received||0);o+=Math.max(Number(e.owed||0)-Number(e.received||0),0)}});tHours.textContent=h.toFixed(2);tPaid.textContent=money(p);tOwed.textContent=money(o);tUnpaid.textContent=db.invoices.filter(i=>i.status!=='paid').length}
function renderCalendar(){monthTitle.textContent=currentMonth.toLocaleDateString(undefined,{month:'long',year:'numeric'});let y=currentMonth.getFullYear(),m=currentMonth.getMonth(),start=new Date(y,m,1,12);start.setDate(1-start.getDay());let names=['SUN','MON','TUE','WED','THU','FRI','SAT'];let h='<div class="days">'+names.map(n=>`<div class="dn">${n}</div>`).join('')+'</div><div class="month">';for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let day=iso(d),items=db.entries.filter(e=>e.date===day);h+=`<div class="day ${day===selectedDate?'selected':''} ${day===iso(new Date())?'today':''}" onclick="selectDay('${day}')"><small>${d.getDate()}</small>${items.slice(0,3).map(e=>`<div class="pill ${e.type}" onclick="event.stopPropagation();loadEntry('${e.id}')">${esc(e.desc||e.type)} ${e.start||''}</div>`).join('')}</div>`}calendar.innerHTML=h+'</div>'}
function moveMonth(n){currentMonth.setMonth(currentMonth.getMonth()+n);renderCalendar()}
function selectDay(d){autoSaveNow();selectedDate=d;newEntry(d);render()}
function renderAgenda(){selectedDayLabel.textContent=new Date(selectedDate+'T12:00').toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});let arr=db.entries.filter(e=>e.date===selectedDate);dayAgenda.innerHTML=arr.length?arr.map(e=>`<div class="agendaItem" onclick="loadEntry('${e.id}')"><b>${esc(e.start||'--')} ${esc(e.desc||e.type)}</b><br><small>${e.type}${e.hours?' • '+e.hours+'h':''}</small></div>`).join(''):'<p class="small">No jobs/events for this day.</p>'}
function calcDiff(a,b){if(!a||!b)return'';let[ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number),mins=bh*60+bm-ah*60-am;if(mins<0)mins+=1440;return(mins/60).toFixed(mins%60?2:0)}
function calcHours(){let h=calcDiff(entryStart.value,entryEnd.value);if(h)entryHours.value=h}
function toggleJobFields(){jobFields.classList.toggle('hidden',entryType.value==='personal')}
function entryObj(){calcHours();return{id:entryId.value||uid(),date:entryDate.value||selectedDate,type:entryType.value,desc:entryDesc.value,start:entryStart.value,end:entryEnd.value,hours:entryHours.value,owed:entryOwed.value,received:entryReceived.value,client:entryClient.value,phone:entryPhone.value,address:entryAddress.value,notes:entryNotes.value}}
function newEntry(d=selectedDate){entryId.value='';entryDate.value=d;entryType.value='scheduled';entryDesc.value='';entryStart.value='';entryEnd.value='';entryHours.value='';entryOwed.value='';entryReceived.value='';entryClient.value='';entryPhone.value='';entryAddress.value='';entryNotes.value='';toggleJobFields()}
function saveEntry(){let e=entryObj();if(!e.desc&&!e.client&&!e.start)return;let i=db.entries.findIndex(x=>x.id===e.id);i>=0?db.entries[i]=e:db.entries.push(e);entryId.value=e.id;selectedDate=e.date;save();render()}
function autoSaveEntry(){clearTimeout(autoTimer);autoTimer=setTimeout(saveEntry,500)}
function autoSaveNow(){clearTimeout(autoTimer);saveEntry()}
function loadEntry(id){let e=db.entries.find(x=>x.id===id);if(!e)return;selectedDate=e.date;entryId.value=e.id;entryDate.value=e.date;entryType.value=e.type;entryDesc.value=e.desc;entryStart.value=e.start;entryEnd.value=e.end;entryHours.value=e.hours;entryOwed.value=e.owed;entryReceived.value=e.received;entryClient.value=e.client;entryPhone.value=e.phone;entryAddress.value=e.address;entryNotes.value=e.notes;clientFocus.value=e.client||'';toggleJobFields();render()}
function deleteEntry(){if(!entryId.value)return;db.entries=db.entries.filter(e=>e.id!==entryId.value);save();newEntry();render()}
function renderTasks(){let arr=db.tasks[selectedDate]||[];taskList.innerHTML=arr.map((t,i)=>`<div class="taskRow ${t.done?'taskDone':''}"><input type="checkbox" ${t.done?'checked':''} onchange="db.tasks['${selectedDate}'][${i}].done=this.checked;save();renderTasks()"><input type="text" value="${esc(t.text)}" onchange="db.tasks['${selectedDate}'][${i}].text=this.value;save()"><button class="bad" onclick="db.tasks['${selectedDate}'].splice(${i},1);save();renderTasks()">×</button></div>`).join('')||'<p class="small">No tasks.</p>'}
function addTask(){let t=newTask.value.trim();if(!t)return;(db.tasks[selectedDate]||(db.tasks[selectedDate]=[])).push({text:t,done:false});newTask.value='';save();renderTasks()}
function renderClientList(){let set=new Set();db.entries.forEach(e=>e.client&&set.add(e.client));db.invoices.forEach(i=>i.client&&set.add(i.client));clientList.innerHTML=[...set].sort().map(n=>`<option value="${esc(n)}"></option>`).join('')}
function renderClientArea(){let n=(clientFocus.value||entryClient.value||'').trim();if(entryClient.value&&!clientFocus.value)clientFocus.value=entryClient.value;let h=0,p=0,o=0;db.entries.forEach(e=>{if(e.client===n&&e.type==='completed'){h+=Number(e.hours||0);p+=Number(e.received||0);o+=Math.max(Number(e.owed||0)-Number(e.received||0),0)}});let invs=db.invoices.filter(i=>i.client===n);invs.forEach(i=>{p+=Number(i.amountPaid||0);o+=Number(i.balance||0)});cHours.textContent=h.toFixed(2);cPaid.textContent=money(p);cOwed.textContent=money(o);clientDetails.innerHTML=n?`<p>Client: <b>${esc(n)}</b></p>`:'<p class="small">No client selected.</p>';clientInvoices.innerHTML=invs.length?invs.map(i=>`<div class="clientInvoiceCard ${i.status}" onclick="showView('invoices');loadInvoice('${i.id}')">${esc(i.date)} • ${money(i.total)} • ${i.status}</div>`).join(''):'<p class="small">No invoices for this client.</p>'}
function newInvoiceForClient(){showView('invoices');newInvoice();let n=clientFocus.value||entryClient.value;invClient.value=n;let e=[...db.entries].reverse().find(x=>x.client===n);if(e){invPhone.value=e.phone||'';invAddress.value=e.address||''}renderInvoicePreview()}
function find(arr,n,obj){let x=arr.find(a=>a.name===n);if(!x){x={name:n,...obj};arr.push(x)}return x}
function remove(arr,n){let i=arr.findIndex(a=>a.name===n);if(i>=0)arr.splice(i,1)}
function renderInvoiceBuilder(){renderServices();renderSupplies();renderEquipment();renderLabor();calcInvoice()}
function renderServices(){servicesBox.innerHTML=db.services.map(n=>`<div class="checkRow"><input type="checkbox" ${activeServices.some(x=>x.name===n)?'checked':''} onchange="this.checked?find(activeServices,'${safe(n)}',{}):remove(activeServices,'${safe(n)}');renderInvoiceBuilder();autoSaveInvoice()"><b>${esc(n)}</b></div>`).join('')}
function renderSupplies(){suppliesBox.innerHTML=db.supplies.map(n=>{let x=activeSupplies.find(a=>a.name===n)||{};return`<div class="supplyRow"><input type="checkbox" ${activeSupplies.some(a=>a.name===n)?'checked':''} onchange="this.checked?find(activeSupplies,'${safe(n)}',{used:'',cost:''}):remove(activeSupplies,'${safe(n)}');renderInvoiceBuilder();autoSaveInvoice()"><b>${esc(n)}</b><input placeholder="used" value="${esc(x.used||'')}" oninput="find(activeSupplies,'${safe(n)}',{used:'',cost:''}).used=this.value;renderInvoicePreview();autoSaveInvoice()"><input type="number" step="0.01" placeholder="$ cost" value="${esc(x.cost||'')}" oninput="find(activeSupplies,'${safe(n)}',{used:'',cost:''}).cost=this.value;calcInvoice();autoSaveInvoice()"></div>`}).join('')+`<div class="miniTotal">Supplies: ${money(activeSupplies.reduce((a,s)=>a+Number(s.cost||0),0))}</div>`}
function renderEquipment(){equipmentBox.innerHTML=db.equipment.map(n=>`<div class="checkRow"><input type="checkbox" ${activeEquipment.some(x=>x.name===n)?'checked':''} onchange="this.checked?find(activeEquipment,'${safe(n)}',{}):remove(activeEquipment,'${safe(n)}');renderInvoicePreview();autoSaveInvoice()"><b>${esc(n)}</b></div>`).join('')}
function renderLabor(){laborBox.innerHTML=db.labor.map(n=>{let x=activeLabor.find(a=>a.name===n)||{};return`<div class="laborRow"><input type="checkbox" ${activeLabor.some(a=>a.name===n)?'checked':''} onchange="this.checked?find(activeLabor,'${safe(n)}',{value:'',cost:''}):remove(activeLabor,'${safe(n)}');renderInvoiceBuilder();autoSaveInvoice()"><b>${esc(n)}</b><input placeholder="value" value="${esc(x.value||'')}" oninput="find(activeLabor,'${safe(n)}',{value:'',cost:''}).value=this.value;renderInvoicePreview();autoSaveInvoice()"><input type="number" step="0.01" placeholder="$ labor" value="${esc(x.cost||'')}" oninput="find(activeLabor,'${safe(n)}',{value:'',cost:''}).cost=this.value;calcInvoice();autoSaveInvoice()"></div>`}).join('')+`<div class="miniTotal">Labor: ${money(activeLabor.reduce((a,l)=>a+Number(l.cost||0),0))}</div>`}
function addMaster(kind){let input={services:serviceAdd,supplies:supplyAdd,equipment:equipmentAdd,labor:laborAdd}[kind];let n=input.value.trim();if(n&&!db[kind].includes(n))db[kind].push(n);input.value='';save();renderInvoiceBuilder()}
function totalInvoice(){return activeSupplies.reduce((a,s)=>a+Number(s.cost||0),0)+activeLabor.reduce((a,l)=>a+Number(l.cost||0),0)}
function calcInvoice(){let total=totalInvoice(),paid=Number(invAmountPaid.value||0),bal=Math.max(total-paid,0);invTotal.textContent=money(total);invPaid.textContent=money(paid);invBalance.textContent=money(bal);if(paid>=total&&total>0)invStatus.value='paid';renderInvoicePreview()}
function newInvoice(){invoiceId.value='';invClient.value='';invPhone.value='';invAddress.value='';invDate.value=iso(new Date());invStatus.value='unpaid';invPayMethod.value='';invAmountPaid.value='';invNotes.value='';checkPhotoData='';checkPhotoPreview.classList.add('hidden');activeServices=[];activeSupplies=[];activeEquipment=[];activeLabor=[];renderInvoiceBuilder();clearSignature(false)}
function invoiceObj(){let total=totalInvoice(),paid=Number(invAmountPaid.value||0);return{id:invoiceId.value||uid(),client:invClient.value,phone:invPhone.value,address:invAddress.value,date:invDate.value,status:invStatus.value,payMethod:invPayMethod.value,amountPaid:paid,balance:Math.max(total-paid,0),total,services:structuredClone(activeServices),supplies:structuredClone(activeSupplies),equipment:structuredClone(activeEquipment),labor:structuredClone(activeLabor),notes:invNotes.value,signature:sigCanvas?sigCanvas.toDataURL('image/png'):'',checkPhoto:checkPhotoData}}
function saveInvoice(){let inv=invoiceObj();if(!inv.client&&!inv.services.length&&!inv.supplies.length&&!inv.labor.length)return;let idx=db.invoices.findIndex(i=>i.id===inv.id);idx>=0?db.invoices[idx]=inv:db.invoices.push(inv);invoiceId.value=inv.id;save();renderInvoices();renderClientArea();renderInvoicePreview()}
function autoSaveInvoice(){clearTimeout(autoInvTimer);autoInvTimer=setTimeout(saveInvoice,600)}
function loadInvoice(id){let i=db.invoices.find(x=>x.id===id);if(!i)return;invoiceId.value=i.id;invClient.value=i.client;invPhone.value=i.phone;invAddress.value=i.address;invDate.value=i.date;invStatus.value=i.status;invPayMethod.value=i.payMethod;invAmountPaid.value=i.amountPaid;invNotes.value=i.notes;activeServices=structuredClone(i.services||[]);activeSupplies=structuredClone(i.supplies||[]);activeEquipment=structuredClone(i.equipment||[]);activeLabor=structuredClone(i.labor||[]);checkPhotoData=i.checkPhoto||'';if(checkPhotoData){checkPhotoPreview.src=checkPhotoData;checkPhotoPreview.classList.remove('hidden')}else checkPhotoPreview.classList.add('hidden');renderInvoiceBuilder();setupSignature();clearSignature(false);if(i.signature){let img=new Image();img.onload=()=>sigCtx.drawImage(img,0,0,sigCanvas.width,sigCanvas.height);img.src=i.signature}}
function deleteInvoice(){if(!invoiceId.value)return;db.invoices=db.invoices.filter(i=>i.id!==invoiceId.value);save();newInvoice();renderInvoices();renderClientArea()}
function renderInvoicePreview(){let i=invoiceObj();let sr=i.services.map(x=>`<div class="line"><div>${esc(x.name)}</div><div>Included</div></div>`).join('');let ur=i.supplies.map(x=>`<div class="line"><div>${esc(x.name)}<br><small>Used: ${esc(x.used||'')}</small></div><div>${money(x.cost)}</div></div>`).join('');let er=i.equipment.map(x=>`<div class="line"><div>${esc(x.name)}</div><div>Used</div></div>`).join('');let lr=i.labor.map(x=>`<div class="line"><div>${esc(x.name)}<br><small>${esc(x.value||'')}</small></div><div>${money(x.cost)}</div></div>`).join('');invoicePreview.innerHTML=`<h2>Invoice / Receipt</h2><p><b>Date:</b> ${esc(i.date)}<br><b>Client:</b> ${esc(i.client)}<br><b>Phone:</b> ${esc(i.phone)}<br><b>Address:</b> ${esc(i.address)}</p>${sr?'<h3>Services</h3>'+sr:''}${ur?'<h3>Supplies</h3>'+ur:''}${er?'<h3>Equipment</h3>'+er:''}${lr?'<h3>Labor</h3>'+lr:''}<h3>Total Due: ${money(i.total)}</h3><p><b>Paid:</b> ${money(i.amountPaid)} ${i.payMethod?'by '+esc(i.payMethod):''}<br><b>Balance:</b> ${money(i.balance)}<br><b>Status:</b> ${esc(i.status)}</p>${i.notes?'<p><b>Notes:</b> '+esc(i.notes)+'</p>':''}${i.checkPhoto?'<p><b>Check photo attached.</b></p>':''}<p><b>Signature:</b></p>${sigCanvas?`<img src="${sigCanvas.toDataURL('image/png')}" style="max-width:100%;border:1px solid #ccc">`:''}`}
function renderInvoices(){allInvoices.innerHTML=db.invoices.length?db.invoices.map(i=>`<div class="invoiceCard ${i.status}" onclick="loadInvoice('${i.id}')">${esc(i.date)} • ${esc(i.client)} • ${money(i.total)} • ${i.status}</div>`).join(''):'<p class="small">No invoices yet.</p>'}
function payMethodChanged(){checkPhotoArea.classList.toggle('hidden',invPayMethod.value!=='Check');renderInvoicePreview()}
function attachCheckPhoto(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{checkPhotoData=r.result;checkPhotoPreview.src=checkPhotoData;checkPhotoPreview.classList.remove('hidden');renderInvoicePreview();saveInvoice()};r.readAsDataURL(f)}
function shareText(){let i=invoiceObj();return `Invoice for ${i.client}\\nDate: ${i.date}\\nTotal: ${money(i.total)}\\nPaid: ${money(i.amountPaid)}\\nBalance: ${money(i.balance)}\\nStatus: ${i.status}`}
function shareInvoice(type){let txt=encodeURIComponent(shareText());if(type==='sms')location.href='sms:?body='+txt;else if(type==='email')location.href='mailto:?subject=Invoice&body='+txt;else if(navigator.share)navigator.share({title:'Invoice',text:decodeURIComponent(txt)});else alert(decodeURIComponent(txt))}
function backup(){download('work-planner-backup.json',JSON.stringify(db,null,2))}
function exportInvoices(){download('invoices.json',JSON.stringify(db.invoices,null,2))}
function download(n,t){let b=new Blob([t],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)}
function setupSignature(){sigCanvas=signaturePad;if(!sigCanvas)return;let r=sigCanvas.getBoundingClientRect();sigCanvas.width=Math.max(300,Math.floor(r.width*2));sigCanvas.height=280;sigCtx=sigCanvas.getContext('2d');sigCtx.lineWidth=4;sigCtx.lineCap='round';sigCtx.strokeStyle='#111';sigCanvas.onpointerdown=e=>{drawing=true;let p=sigPoint(e);sigCtx.beginPath();sigCtx.moveTo(p.x,p.y)};sigCanvas.onpointermove=e=>{if(!drawing)return;let p=sigPoint(e);sigCtx.lineTo(p.x,p.y);sigCtx.stroke()};sigCanvas.onpointerup=()=>{drawing=false;renderInvoicePreview();saveInvoice()};sigCanvas.onpointerleave=()=>drawing=false}
function sigPoint(e){let r=sigCanvas.getBoundingClientRect();return{x:(e.clientX-r.left)*(sigCanvas.width/r.width),y:(e.clientY-r.top)*(sigCanvas.height/r.height)}}
function clearSignature(update=true){if(!sigCtx)setupSignature();if(sigCtx){sigCtx.clearRect(0,0,sigCanvas.width,sigCanvas.height);if(update){renderInvoicePreview();saveInvoice()}}}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}
render();
